---
apiVersion: v1
kind: Service
metadata:
  name: pod-service
  namespace: staging
spec:
  ports:
    - port: 80
      targetPort: 3000  #mapare port 80:3000
      protocol: TCP
  type: NodePort  #you need to use it in order to make use of an AWS Load balancer
  selector:
    app: pod-info